// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHcMZ_Sn6elnXjB_GSrYxUn19VQFbD1ng',
    appId: '1:812299628522:web:8b28a537c9c9f0e06b8c93',
    messagingSenderId: '812299628522',
    projectId: 'ejemplo2023i-af81b',
    authDomain: 'ejemplo2023i-af81b.firebaseapp.com',
    storageBucket: 'ejemplo2023i-af81b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDomxAeHGb82Scac_eK_7itb5bukXVsIcE',
    appId: '1:812299628522:android:be504c11b1915d556b8c93',
    messagingSenderId: '812299628522',
    projectId: 'ejemplo2023i-af81b',
    storageBucket: 'ejemplo2023i-af81b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeZwWHOpkZbiKE3UBWAJ31Nb0q--hQea0',
    appId: '1:812299628522:ios:671d0ecca80db7aa6b8c93',
    messagingSenderId: '812299628522',
    projectId: 'ejemplo2023i-af81b',
    storageBucket: 'ejemplo2023i-af81b.appspot.com',
    iosClientId: '812299628522-1ih26ecfj9agqo0q6dpldsdl0d1n6gb4.apps.googleusercontent.com',
    iosBundleId: 'com.edson.ejemplo2023i',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDeZwWHOpkZbiKE3UBWAJ31Nb0q--hQea0',
    appId: '1:812299628522:ios:671d0ecca80db7aa6b8c93',
    messagingSenderId: '812299628522',
    projectId: 'ejemplo2023i-af81b',
    storageBucket: 'ejemplo2023i-af81b.appspot.com',
    iosClientId: '812299628522-1ih26ecfj9agqo0q6dpldsdl0d1n6gb4.apps.googleusercontent.com',
    iosBundleId: 'com.edson.ejemplo2023i',
  );
}
